apiVersion: v1
kind: ConfigMap
metadata:
  name: multiwerf-data
data:
  multiwerf.json: |
    {{ $.Files.Get "multiwerf.json" | fromJson| toJson }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trdl-data
data:
  trdl_channels.yaml: |
{{ $.Files.Get "trdl_channels.yaml" | indent 4 }}
