type: object
required:
  - giterminismConfigVersion
additionalProperties: {}
properties:
  giterminismConfigVersion:
    type: string
    enum: ["1"]
  config:
    $ref: '#/definitions/Config'
definitions:
  Config:
    type: object
    additionalProperties: {}
    properties:
      allowUncommitted:
        type: boolean
      stapel:
        $ref: '#/definitions/ConfigStapel'
  ConfigStapel:
    type: object
    additionalProperties: {}
    properties:
      mount:
        $ref: '#/definitions/ConfigStapelMount'
  ConfigStapelMount:
    type: object
    additionalProperties: {}
    properties:
      allowBuildDir:
        type: boolean
      allowFromPaths:
        type: array
        items:
          type: string