apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy1-{{ env "WERF_PROJECT_NAME" }}
  annotations:
    "werf.io/set-replicas-only-on-creation": "true"
    "werf.io/set-resources-only-on-creation": "true"
  labels:
    service: mydeploy1-{{ env "WERF_PROJECT_NAME" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mydeploy1-{{ env "WERF_PROJECT_NAME" }}
  template:
    metadata:
      labels:
        service: mydeploy1-{{ env "WERF_PROJECT_NAME" }}
    spec:
      containers:
      - name: main
        command: [ "/bin/bash", "-c", "while true; do date ; sleep 1 ; done" ]
        image: ubuntu:18.04
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "10m"
