run:
  timeout: 10m

linters-settings:
  gocritic:
    disabled-checks:
      - dupBranchBody
  gci:
    local-prefixes: github.com/werf/

linters:
  disable-all: true
  enable:
    - deadcode
    - structcheck
    - typecheck
    - varcheck

    - asciicheck
    - bidichk
    - bodyclose
    - errname
    - exportloopref
    - gci
    - gocritic
    - gofumpt