run:
  timeout: 10m

linters-settings:
  gocritic:
    disabled-checks:
      - dupBranchBody

linters:
  disable-all: true
  enable:
    - deadcode
    - structcheck
    - typecheck
    - varcheck
    - gocritic