AllCops:
  TargetRubyVersion: 2.1

Metrics/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 85

Metrics/MethodLength:
  Max: 50

Metrics/ModuleLength:
  Max: 150

Metrics/ClassLength:
  Max: 300

Metrics/BlockLength:
  Max: 50

Security/MarshalLoad:
  Enabled: false

Security/JSONLoad:
  Enabled: false

Style/FileName:
  Exclude:
    - 'spec/chef/testproject/recipes/**/*'

Style/DoubleNegation:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/SpaceInsideParens:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/CaseIndentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Documentation:
  Enabled: false

EmptyMethod:
  Enabled: false
