apiVersion: v1
kind: ConfigMap
data:
  json: {{ .Values.json }}
  quoted: {{ .Values.quoted | quote }}
  int: {{ .Values.int | b64enc }}
  secret_file: {{ tuple "saml/tls.key" . | include "werf_secret_file" | b64enc }}
