apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy1-{{ env "WERF_PROJECT_NAME" }}
  labels:
    service: mydeploy1-{{ env "WERF_PROJECT_NAME" }}
  annotations:
    "werf.io/show-service-messages": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      service: mydeploy1-{{ env "WERF_PROJECT_NAME" }}
  template:
    metadata:
      labels:
        service: mydeploy1-{{ env "WERF_PROJECT_NAME" }}
    spec:
      initContainers:
      - name: init
        command: [ "/bin/bash", "-c", "for i in {1..2} ; do date; sleep 1; done" ]
        image: ubuntu:18.04
      containers:
      - name: main
        command: [ "/bin/bash", "-c", "while true; do date ; sleep 1 ; done" ]
        image: ubuntu:18.04
