configVersion: 1
project: ansible-yum1
{{- range $_, $centosVersion := (list "6" "7") }}
---
image: centos-{{ $centosVersion }}
from: centos:{{ $centosVersion }}
ansible:
  install:
  - name: "Install a package using yum"
    yum:
      name: httpd
      state: latest
{{- end }}
