en:
  common:
    image:
      signature: "signature: %{signature}"
      info: "date: %{date}\nsize: %{size} MB"
      commands: "commands:"
    process:
      git_artifact_loading: 'loading git_artifact'
      chefdk_loading: 'loading chefdk'
      berks_vendor: 'berks_vendor'
      git_artifact_fetch: "fetching remote git_artifact '%{name}'"
    status:
      process:
        pushing: '[PUSHING]'
        building: '[BUILDING]'
        default: '[RUNNING]'
      success:
        default: '[OK]'
      failed:
        default: '[FAILED]'
    state:
      using_cache: '[USING CACHE]'
      build: '[BUILD]'
      push: '[PUSH]'
    introspect:
      stage: "Introspect stage '%{name}'"
