en:
  common:
    process:
      loading_git_artifact: 'loading gitartifact'
      loading_chefdk: 'loading chefdk'
      berks_vendor: 'berks_vendor'
      git_artifact_fetch: "fetching remote git_artifact '%{name}'"
    status:
      process:
        pushing: '[PUSHING]'
        building: '[BUILDING]'
        default: '[RUNNING]'
      success:
        default: '[OK]'
      failed:
        default: '[FAILED]'
    state:
      using_cache: '[USING CACHE]'
      build: '[BUILD]'
