en:
  common:
    image:
      signature: "signature: %{signature}"
      info:
        date: "date: %{value}"
        size: "size: %{value} MB"
        difference: "difference: %{value} MB"
      commands: "commands:"
    process:
      artifact_copy: "copying artifact '%{name}'"
      git_artifact_loading: 'loading git_artifact'
      git_artifact_clone: "cloning remote git_artifact '%{name}'"
      git_artifact_fetch: "fetching remote git_artifact '%{name}'"
      chefdk_loading: 'loading chefdk'
      berks_vendor: 'berks_vendor'
    status:
      process:
        pushing: '[PUSHING]'
        building: '[BUILDING]'
        default: '[RUNNING]'
      success:
        default: '[OK]'
      failed:
        default: '[FAILED]'
    state:
      using_cache: '[USING CACHE]'
      not_present: '[NOT PRESENT]'
      build: '[BUILD]'
      push: '[PUSH]'
    introspect:
      stage: "Introspect stage '%{name}'"
