en:
  common:
    image:
      signature: "signature: %{signature}"
      info:
        date: "date: %{value}"
        size: "size: %{value} MB"
        difference: "difference: %{value} MB"
      commands: "commands:"
    process:
      artifact_copy: "copying artifact '%{name}'"
      artifact_building: "building artifact '%{name}'"
      git_artifact_clone: "cloning remote git_artifact '%{name}'"
      git_artifact_fetch: "fetching remote git_artifact '%{name}'"
      berks_vendor: 'berks_vendor'
      gitartifact_container_loading: 'loading dappdeps/gitartifact container'
      chefdk_container_loading: 'loading dappdeps/chefdk container'
      system_shellout_container_loading: 'loading system shellout container'
    status:
      process:
        pushing: '[PUSHING]'
        building: '[BUILDING]'
        default: '[RUNNING]'
      success:
        default: '[OK]'
      failed:
        default: '[FAILED]'
    state:
      using_cache: '[USING CACHE]'
      not_present: '[NOT PRESENT]'
      build: '[BUILD]'
      empty: '[EMPTY]'
      push: '[PUSH]'
