en:
  common:
    image:
      signature: "signature: %{signature}"
      info:
        date: "date: %{value}"
        size: "size: %{value} MB"
        difference: "difference: %{value} MB"
      commands: "commands:"
    process:
      artifact_copy: "copying artifact '%{name}'"
      artifact_building: "building artifact '%{name}'"
      git_artifact_loading: 'loading git_artifact'
      git_artifact_clone: "cloning remote git_artifact '%{name}'"
      git_artifact_fetch: "fetching remote git_artifact '%{name}'"
      chefdk_loading: 'loading chefdk'
      berks_vendor: 'berks vendor'
      waiting_resouce_lock: "waiting for locked resource '%{basename}/%{name}'"
    status:
      process:
        pushing: '[PUSHING]'
        building: '[BUILDING]'
        default: '[RUNNING]'
      success:
        default: '[OK]'
      failed:
        default: '[FAILED]'
    state:
      using_cache: '[USING CACHE]'
      not_present: '[NOT PRESENT]'
      build: '[BUILD]'
      empty: '[EMPTY]'
      push: '[PUSH]'
    warning:
      excess_builder_instruction: "WARNING: Excessive use of the 'builder' instruction. Builder type will be automatically determined by the first use of any builder."
      excess_name_instruction: "WARNING: Excessive use of the 'name' instruction. Given name corresponds to default name."
