en:
  net_status:
    missing_translation: "Missing translation for code: '%{code}'!"
    shellout:
      shell_command_failed: ">>> START STREAM\n%{stream}\n>>> END STREAM"
    application:
      application_not_built: "Application hasn't been built yet!"
      application_not_run: "Application run failed!"
      git_branch_without_name: "Application has specific revision that isn't associated with a branch name!"
      ci_environment_required: 'CI environment required (Travis or GitLab CI)!'
      cookbooks_stage_checksum_not_caclculated: "Cookbooks checksum not calculated for stage '%{stage}', run build first"
    dappfile:
      incorrect: "Dappfile with '%{error}':\n%{message}"
    build:
      from_image_required: 'Missing from_image!'
      image_already_untagged: "Image `%{name}` already untagged!"
      image_not_exist: "Image `%{name}` not exist!"
      built_id_not_defined: '`from.built_id` not defined!'
      from_image_not_found: 'Image `%{name}` not found!'
    project:
      spush_command_unexpected_apps_number: "Command 'spush' can process only one application!"
      run_command_unexpected_apps_number: "Command 'run' can process only one application!"
      no_such_app: "No such app: '%{apps_patterns}'!"
      dappfile_not_found: "Dappfile not found!"
      cannot_run_ssh_agent: "Cannot run ssh-agent"
      ssh_key_not_found: "Ssh key '%{path}' not exist!"
      mrproper_required_option: "Expected command option '--all' or '--improper-cache-version-stages'!"
    config:
      builder_type_conflict: 'Conflict between builder types!'
      builder_type_unsupported: "Defined unsupported builder type `%{type}`!"
      docker_from_not_defined: "`docker.from` not defined!"
      artifact_unexpected_attribute: "Artifact doesn't has attribute '%{attr}'!"
      artifact_conflict: "Conflict between artifacts paths!"
      git_artifact_unexpected_attribute: "'%{type}' git artifact doesn't has attribute '%{attr}'!"
      docker_from_incorrect: "`docker.from` has incorrect value `%{name}`: expected format `image_name:tag`!"
      app_name_incorrect: "Application has incorrect name '%{name}': doesn't match regex '%{reg}'!"
    chef:
      stage_path_overlap: "Cannot install '%{cookbook}' cookbook's path %{from} into %{to}: already exists"
    registry:
      incorrect_repo: 'Incorrect repository!'
      no_such_app: 'No such app in registry!'
      authenticate_type_not_supported: 'Registry authenticate type not supported!'
      page_not_found: "Page '%{url}' not found!"
      user_not_authorized: 'User not authorized!'
      response_with_error_status: 'Response with error status!'
      berksfile_absolute_path_forbidden: "Absolute paths in Berksfile are not allowed (cookbook '%{cookbook}', path: '%{path}')"
    lock:
      timeout: "Could not obtain lock for '%{name}' within %{timeout} seconds"
