en:
  net_status:
    missing_translation: "Missing translation for code: '%{code}'!"
    shellout:
      shell_command_failed: ">>> START STREAM\n%{stream}\n>>> END STREAM"
    application:
      application_not_built: "Application hasn't been built yet!"
      application_not_run: "Application run failed!"
      git_branch_without_name: "Application has specific revision that isn't associated with a branch name!"
      ci_environment_required: 'CI environment required (Travis or GitLab CI)!'
    dappfile:
      incorrect: "Dappfile '%{path}' with '%{error}':\n%{message}"
    build:
      from_image_required: 'Missing from_image!'
      image_already_untagged: "Image `%{name}` already untagged!"
      image_not_exist: "Image `%{name}` not exist!"
      another_image_already_tagged: 'Image with other id already tagged!'
      built_id_not_defined: '`from.built_id` not defined!'
    controller:
      spush_command_unexpected_apps_number: "Command 'spush' can process only one application!"
      run_command_unexpected_apps_number: "Command 'run' can process only one application!"
      no_such_app: "No such app: '%{patterns}'!"
      dappfile_not_found: "Dappfile not found!"
    config:
      builder_type_conflict: 'Conflict between builder types!'
      builder_type_unsupported: "Defined unsupported builder type `%{type}`!"
      docker_from_not_defined: "Docker `from` not defined!"
      artifact_unexpected_attribute: "Artifact doesn't has attribute '%{attr}'!"
      git_artifact_unexpected_attribute: "'%{type}' git artifact doesn't has attribute '%{attr}'!"
    chef:
      stage_path_overlap: "Cannot install '%{cookbook}' cookbook's path %{from} into %{to}: already exists"
