en:
  net_status:
    missing_translation: "Missing translation for code: '%{code}'."
    application:
      application_is_not_built: "Application isn't built!"
      git_branch_without_name: "Application has specific revision that isn't associated with a branch name!"
      ci_environment_required: 'CI environment required (Travis or GitLab CI)!'
    build:
      from_image_required: 'Missing from_image!'
      image_is_already_untagged: "Image `%{name}` is already untagged!"
      image_is_not_exist: "Image `%{name}` is not exist!"
      image_is_already_tagged: 'Image with other id has already tagged!'
      built_id_is_not_defined: '`from.built_id` is not defined!'
    controller:
      one_application_expected: "Several applications isn't available for push command!"
      no_such_app: "No such app: '%{patterns}' in '%{path}'!"
      dappfile_not_found: "Dappfile isn't found!"
    config:
      another_builder_defined: 'Already defined another builder type!'
      builder_type_is_not_supported: "Builder type `%{type}` isn't supported!"
      docker_from_is_not_defined: "Docker `from` isn't defined!"
      git_artifact_unexpected_attribute: "'%{type}' git artifact doesn't have attribute '%{attr}'!"