name: Final notification

on:
  workflow_call:

defaults:
  run:
    shell: bash

env:
  DEBIAN_FRONTEND: "noninteractive"

jobs:
  _:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - uses: technote-space/workflow-conclusion-action@v2

    - name: Notify
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ env.WORKFLOW_CONCLUSION }}
        MSG_MINIMAL: "ref,actions url"
