name: Commit tests

on:
  push:
    paths:
    - '.github/workflows/commit_tests.yml'
    - '**/*.go'

jobs:
  unit-test:
    name: Unit testing
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Prepare environment
        run: |
          sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu libbtrfs-dev
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Tests
        run: |
          make unit-tests

  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Prepare environment
        run: |
          sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu libbtrfs-dev
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2

      - name: Lint
        run: |
          make lint

