name: Documentation Validation
on:
  push:
    paths:
      - '.github/workflows/docs_tests.yml'
      - 'cmd/**'
      - 'docs/**'
      - 'README.md'
      - 'README_ru.md'

env:
  DEBIAN_FRONTEND: "noninteractive"
  GOPATH: ${{ github.workspace }}/go

jobs:

  check_cli_and_readme_partials:
    name: Check CLI and README partials
    runs-on: ubuntu-22.04
    steps:
      - name: Install werf build dependencies
        run: sudo apt-get install -y libbtrfs-dev

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: go.mod

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Test
        run: |
          ./scripts/ci/git.sh
          task -p test:go-test paths="./integration/suites/docs"

  check_links:
    name: Check broken links
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: go.mod

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check links
        run: task -p doc:check-broken-links
        env:
          WERF_REPO: "ghcr.io/${{ github.repository_owner }}/werfio"
