name: Documentation Validation
on:
  push:
    paths:
      - '.github/workflows/docs_tests.yml'
      - 'cmd/**'
      - 'docs/**'
      - 'README.md'
      - 'README_ru.md'

env:
  GOPATH: ${{ github.workspace }}/go

jobs:

  check_cli_and_readme_partials:
    name: Check CLI and README partials
    runs-on: ubuntu-latest
    steps:
      - name: Install werf build dependencies
        run: sudo apt-get install -y libbtrfs-dev

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Setup Golang caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - name: Test
        run: |
          ./scripts/ci/git.sh
          ./scripts/ci/go-test.sh ./integration/suites/docs

  check_links:
    name: Check broken links
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lang: [ru, en]
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Setup Golang caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check links
        run: make docs_check_broken_links_${{ matrix.lang }}
        env:
          WERF_REPO: "ghcr.io/${{ github.repository_owner }}/werfio"
