name: Deploy multiwerf.json
on:
  push:
    branches:
    - multiwerf

jobs:

  deploy_multiwerf_to_prod:
    name: Deploy multiwerf.json to prod
    runs-on: tfprod-werf
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Werf converge
      uses: werf/actions/converge@v1.2
      with:
        env: production
      env:
        WERF_NAMESPACE: "werfio-production"
        WERF_KUBE_CONTEXT: prod
        WERF_DIR: "ci"
