name: Site deployment
on:
  pull_request:
    types: [labeled]
  push:
    branches:
    - multiwerf
  release:
    types: [published]

jobs:
  stub:
    name: Greeting
    runs-on: ubuntu-latest
    steps:

    - name: Greeting
      run: echo "This job is used to prevent the workflow to fail when all other jobs are skipped."

  unlabel:
    name: Optional unlabeling
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.label.id == 1753518893 # review docs label
    steps:

    - uses: actions/github-script@0.3.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const eventLabelName = '${{github.event.label.name}}'
          const response = await github.issues.listLabelsOnIssue({...context.issue})
          for (const label of response.data) {
            if (label.name === eventLabelName) {
              github.issues.removeLabel({...context.issue, name: eventLabelName})
              break
            }
          }

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'release' || (github.event_name == 'pull_request' && github.event.label.id == 1753518893) # review docs label
    steps:

    # TODO: variables[review_sha]=${{ github.sha }} (currently, werf does not fetch PRs' refs)
    - name: Trigger Review Job
      run: |
        curl -X POST \
             -F "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
             -F "ref=master" \
             -F "variables[review_sha]=${{ github.event.pull_request.head.sha }}" \
             ${{ secrets.GITLAB_URL }}/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/trigger/pipeline
      if: github.event_name == 'pull_request' && github.event.label.id == 1753518893 # review docs label

    - name: Trigger Main Job
      run: |
        curl -X POST \
             -F "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
             -F "ref=master" \
             ${{ secrets.GITLAB_URL }}/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/trigger/pipeline
      if: github.event_name == 'push' || github.event_name == 'release'
