name: Site deployment
on:
  push:
    branches:
    - multiwerf
    paths:
    - multiwerf.json

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Trigger Main Job
      run: |
        curl -X POST \
             -F "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
             -F "ref=master" \
             ${{ secrets.GITLAB_URL }}/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/trigger/pipeline
