name: test:pr

on:
  pull_request:
    paths:
    - '.github'
    - '**/*.go'
    - 'go.mod'
  repository_dispatch:
    types: [test:pr]
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml

  unit:
    uses: ./.github/workflows/_test_unit.yml

  notify:
    if: failure()
    uses: ./.github/workflows/_final_notification.yml
    needs:
    - lint
    - unit
    secrets: inherit
