name: Tests
on:
  pull_request:
    types: [labeled]
  repository_dispatch:
    types: [tests]
env:
  GO111MODULE: on

jobs:

  unlabel:
    name: Label taking off
    if: github.event_name == 'pull_request' && github.event.label.name == 'run tests'
    runs-on: ubuntu-latest
    steps:

    - uses: actions/github-script@v1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: "github.issues.removeLabel({...context.issue, name: '${{ github.event.label.name }}' })"

  precompiled_tests_binaries:
    name: Precompiled tests binaries
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'repository_dispatch' || (github.event_name == 'pull_request' && github.event.label.id == 1745044226) # run tests label
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compile tests binaries
      run: |
        # unit tests binaries
        ./scripts/tests/precompiled_tests_binaries.sh ./cmd ./precompiled_tests_binaries/unit
        ./scripts/tests/precompiled_tests_binaries.sh ./pkg ./precompiled_tests_binaries/unit

        # integration tests binaries
        ./scripts/tests/precompiled_tests_binaries.sh ./integration ./precompiled_tests_binaries/integration

        # integration_k8s tests binaries
        ./scripts/tests/precompiled_tests_binaries.sh ./integration_k8s ./precompiled_tests_binaries/integration_k8s
      shell: bash

    - name: Compile tests werf binary (ubuntu-latest)
      run: GOBIN=$PWD ./go-build.sh
      if: matrix.os == 'ubuntu-latest'

    - name: Upload unit tests binaries
      uses: actions/upload-artifact@master
      with:
        name: "${{ matrix.os }}_unit_tests_binaries"
        path: precompiled_tests_binaries/unit

    - name: Upload integration tests binaries
      uses: actions/upload-artifact@master
      with:
        name: "${{ matrix.os }}_integration_tests_binaries"
        path: precompiled_tests_binaries/integration

    - name: Upload integration k8s tests binaries
      uses: actions/upload-artifact@master
      with:
        name: "${{ matrix.os }}_integration_k8s_tests_binaries"
        path: precompiled_tests_binaries/integration_k8s

    - name: Upload werf binary (ubuntu-latest)
      uses: actions/upload-artifact@master
      with:
        name: "${{ matrix.os }}_werf_binary"
        path: werf
      if: matrix.os == 'ubuntu-latest'

  unit_tests:
    name: Unit tests
    needs: precompiled_tests_binaries
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download unit tests binaries
      uses: actions/download-artifact@master
      with:
        name: "${{ matrix.os }}_unit_tests_binaries"
        path: .

    - name: Prepare environment
      run: find . -type f \( -name '*.test' -or -name '*.test.exe' \) -exec chmod +x {} \;
      shell: bash

    - name: Test
      run: |
        test_binaries=$(find . -type f \( -name '*.test' -or -name '*.test.exe' \))
        for test_binary in $test_binaries; do
          $test_binary -test.v
        done
      shell: bash

  integration_tests:
    name: Integration tests
    needs: precompiled_tests_binaries
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        extra-find-args:
        - "-name 'git.test'"
        - "-name 'ansible.test'"
        - "! -name 'git.test' ! -name 'ansible.test'"
    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Checkout code
      uses: actions/checkout@v2
      if: matrix.extra-find-args != '! -name ''git.test'' ! -name ''ansible.test'''

    - name: Checkout code (git history as fixtures for tests)
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      if: matrix.extra-find-args == '! -name ''git.test'' ! -name ''ansible.test'''

    - name: Download integration tests binaries
      uses: actions/download-artifact@master
      with:
        name: "${{ matrix.os }}_integration_tests_binaries"
        path: .

    - name: Download werf binary
      uses: actions/download-artifact@master
      with:
        name: "${{ matrix.os }}_werf_binary"
        path: .

    - name: Prepare environment
      run: |
        ./scripts/ci/git.sh

        go build github.com/onsi/ginkgo/ginkgo

        chmod +x werf
        find integration -type f -name '*.test' -exec chmod +x {} \;
      shell: bash

    - name: Test
      run: |
        test_binaries=$(find integration -type f -name '*.test' ${{ matrix.extra-find-args }})
        WERF_TEST_BINARY_PATH=$GITHUB_WORKSPACE/werf ./ginkgo -p -keepGoing $test_binaries
      shell: bash

  integration_k8s_tests:
    name: Integration k8s tests
    needs: precompiled_tests_binaries
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        k8s_version: [1.16, 1.17, 1.18, 1.19]

    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download integration k8s tests binaries
      uses: actions/download-artifact@master
      with:
        name: "${{ matrix.os }}_integration_k8s_tests_binaries"
        path: .

    - name: Download werf binary
      uses: actions/download-artifact@master
      with:
        name: "${{ matrix.os }}_werf_binary"
        path: .

    - name: Prepare environment
      run: |
        ./scripts/ci/git.sh

        go build github.com/onsi/ginkgo/ginkgo

        find integration_k8s -type f -name '*.test' -exec chmod +x {} \;

        chmod +x werf

        echo WERF_TEST_K8S_BASE64_KUBECONFIG=$(printenv WERF_TEST_K8S_BASE64_KUBECONFIG_$(echo ${{ matrix.k8s_version }} | tr . _)) >> $GITHUB_ENV
      shell: bash
      env:
        WERF_TEST_K8S_BASE64_KUBECONFIG_1_16: ${{ secrets.WERF_TEST_K8S_BASE64_KUBECONFIG_1_16 }}
        WERF_TEST_K8S_BASE64_KUBECONFIG_1_17: ${{ secrets.WERF_TEST_K8S_BASE64_KUBECONFIG_1_17 }}
        WERF_TEST_K8S_BASE64_KUBECONFIG_1_18: ${{ secrets.WERF_TEST_K8S_BASE64_KUBECONFIG_1_18 }}
        WERF_TEST_K8S_BASE64_KUBECONFIG_1_19: ${{ secrets.WERF_TEST_K8S_BASE64_KUBECONFIG_1_19 }}

    - name: Test
      run: |
        source ./scripts/ci/integration_k8s_tests_before_hook.sh
        test_binaries=$(find integration_k8s -type f -name '*.test')
        WERF_TEST_BINARY_PATH=$GITHUB_WORKSPACE/werf ./ginkgo -p -keepGoing $test_binaries
      shell: bash
      env:
        WERF_TEST_K8S_DOCKER_REGISTRY: ${{ secrets.WERF_TEST_K8S_DOCKER_REGISTRY }}
        WERF_TEST_K8S_DOCKER_REGISTRY_USERNAME: ${{ secrets.WERF_TEST_K8S_DOCKER_REGISTRY_USERNAME }}
        WERF_TEST_K8S_DOCKER_REGISTRY_PASSWORD: ${{ secrets.WERF_TEST_K8S_DOCKER_REGISTRY_PASSWORD }}

  integration_k8s_per_registry_implementation_tests:
    name: Integration k8s per registry implementation tests
    needs: precompiled_tests_binaries
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        k8s_version: [1.16, 1.17, 1.18, 1.19]
        implementation:
          - acr
          - default
          - dockerhub
          - ecr
          - gcr
  #        - github
          - harbor
          - quay

    runs-on: ${{ matrix.os }}
    env:
      WERF_TEST_DOCKER_REGISTRY_IMPLEMENTATION_ACR: 1
      WERF_TEST_ACR_PASSWORD: ${{ secrets.WERF_TEST_ACR_PASSWORD }}
      WERF_TEST_ACR_REGISTRY: ${{ secrets.WERF_TEST_ACR_REGISTRY }}
      WERF_TEST_ACR_USERNAME: ${{ secrets.WERF_TEST_ACR_USERNAME }}

      WERF_TEST_DOCKER_REGISTRY_IMPLEMENTATION_DEFAULT: 1
      WERF_TEST_DEFAULT_PASSWORD: ${{ secrets.WERF_TEST_DEFAULT_PASSWORD }}
      WERF_TEST_DEFAULT_REGISTRY: ${{ secrets.WERF_TEST_DEFAULT_REGISTRY }}
      WERF_TEST_DEFAULT_USERNAME: ${{ secrets.WERF_TEST_DEFAULT_USERNAME }}

      WERF_TEST_DOCKER_REGISTRY_IMPLEMENTATION_DOCKERHUB: 1
      WERF_TEST_DOCKERHUB_PASSWORD: ${{ secrets.WERF_TEST_DOCKERHUB_PASSWORD }}
      WERF_TEST_DOCKERHUB_REGISTRY: ${{ secrets.WERF_TEST_DOCKERHUB_REGISTRY }}
      WERF_TEST_DOCKERHUB_USERNAME: ${{ secrets.WERF_TEST_DOCKERHUB_USERNAME }}

      WERF_TEST_DOCKER_REGISTRY_IMPLEMENTATION_ECR: 1
      WERF_TEST_ECR_REGISTRY: ${{ secrets.WERF_TEST_ECR_REGISTRY }}
      WERF_TEST_ECR_PASSWORD: ${{ secrets.WERF_TEST_ECR_PASSWORD }}
      WERF_TEST_ECR_USERNAME: ${{ secrets.WERF_TEST_ECR_USERNAME }}

      WERF_TEST_DOCKER_REGISTRY_IMPLEMENTATION_GCR: 1
      WERF_TEST_GCR_BASE64_CONFIG: ${{ secrets.WERF_TEST_GCR_BASE64_CONFIG }}
      WERF_TEST_GCR_REGISTRY: ${{ secrets.WERF_TEST_GCR_REGISTRY }}

      WERF_TEST_DOCKER_REGISTRY_IMPLEMENTATION_GITHUB: 1
      WERF_TEST_GITHUB_PASSWORD: ${{ secrets.WERF_TEST_GITHUB_PASSWORD }}
      WERF_TEST_GITHUB_REGISTRY: ${{ secrets.WERF_TEST_GITHUB_REGISTRY }}
      WERF_TEST_GITHUB_TOKEN: ${{ secrets.WERF_TEST_GITHUB_TOKEN }}
      WERF_TEST_GITHUB_USERNAME: ${{ secrets.WERF_TEST_GITHUB_USERNAME }}

      WERF_TEST_DOCKER_REGISTRY_IMPLEMENTATION_HARBOR: 1
      WERF_TEST_HARBOR_PASSWORD: ${{ secrets.WERF_TEST_HARBOR_PASSWORD }}
      WERF_TEST_HARBOR_REGISTRY: ${{ secrets.WERF_TEST_HARBOR_REGISTRY }}
      WERF_TEST_HARBOR_USERNAME: ${{ secrets.WERF_TEST_HARBOR_USERNAME }}

      WERF_TEST_DOCKER_REGISTRY_IMPLEMENTATION_QUAY: 1
      WERF_TEST_QUAY_PASSWORD: ${{ secrets.WERF_TEST_QUAY_PASSWORD }}
      WERF_TEST_QUAY_REGISTRY: ${{ secrets.WERF_TEST_QUAY_REGISTRY }}
      WERF_TEST_QUAY_TOKEN: ${{ secrets.WERF_TEST_QUAY_TOKEN }}
      WERF_TEST_QUAY_USERNAME: ${{ secrets.WERF_TEST_QUAY_USERNAME }}
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download integration k8s tests binaries
      uses: actions/download-artifact@master
      with:
        name: "${{ matrix.os }}_integration_k8s_tests_binaries"
        path: .

    - name: Download werf binary
      uses: actions/download-artifact@master
      with:
        name: "${{ matrix.os }}_werf_binary"
        path: .

    - name: Login (acr)
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      if: matrix.implementation == 'acr'

    - name: Login (ecr)
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      if: matrix.implementation == 'ecr'

    - name: Prepare environment
      run: |
        ./scripts/ci/git.sh
        ./scripts/ci/integration_tests_registries_login.sh ${{ matrix.implementation }}

        go build github.com/onsi/ginkgo/ginkgo

        find integration_k8s -type f -name '*.test' -exec chmod +x {} \;

        chmod +x werf

        echo WERF_TEST_K8S_BASE64_KUBECONFIG=$(printenv WERF_TEST_K8S_BASE64_KUBECONFIG_$(echo ${{ matrix.k8s_version }} | tr . _)) >> $GITHUB_ENV
      shell: bash
      env:
        WERF_TEST_K8S_BASE64_KUBECONFIG_1_16: ${{ secrets.WERF_TEST_K8S_BASE64_KUBECONFIG_1_16 }}
        WERF_TEST_K8S_BASE64_KUBECONFIG_1_17: ${{ secrets.WERF_TEST_K8S_BASE64_KUBECONFIG_1_17 }}
        WERF_TEST_K8S_BASE64_KUBECONFIG_1_18: ${{ secrets.WERF_TEST_K8S_BASE64_KUBECONFIG_1_18 }}
        WERF_TEST_K8S_BASE64_KUBECONFIG_1_19: ${{ secrets.WERF_TEST_K8S_BASE64_KUBECONFIG_1_19 }}

    - name: Test
      run: |
        source ./scripts/ci/integration_k8s_tests_before_hook.sh
        # NOTE: integration_k8s/bundles only for now!
        test_binaries=$(find integration_k8s/bundles -type f -name '*.test')
        WERF_TEST_BINARY_PATH=$GITHUB_WORKSPACE/werf ./ginkgo -p -keepGoing $test_binaries
      shell: bash
      env:
        WERF_TEST_K8S_DOCKER_REGISTRY: ${{ secrets.WERF_TEST_K8S_DOCKER_REGISTRY }}
        WERF_TEST_K8S_DOCKER_REGISTRY_USERNAME: ${{ secrets.WERF_TEST_K8S_DOCKER_REGISTRY_USERNAME }}
        WERF_TEST_K8S_DOCKER_REGISTRY_PASSWORD: ${{ secrets.WERF_TEST_K8S_DOCKER_REGISTRY_PASSWORD }}
