name: Trdl publisher
on:
  push:
    branches:
    - multiwerf

jobs:
  release:
    name: Publish release channels using trdl server
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      uses: werf/trdl-vault-actions/publish@main
      with:
        vault-addr: ${{ secrets.TRDL_VAULT_ADDR }}
        project-name: werf
        vault-auth-method: approle
        vault-role-id: ${{ secrets.TRDL_VAULT_ROLE_ID }}
        vault-secret-id: ${{ secrets.TRDL_VAULT_SECRET_ID }}

  deploy_channels_cm_prod:
    name: Deploy multiwerf.json and trdl_channels.yaml to production
    needs: release
    runs-on: tfprod-werf
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Converge
      uses: werf/actions/converge@v1.2
      with:
        env: production
      env:
        WERF_NAMESPACE: "werfio-production"
        WERF_KUBE_CONTEXT: prod
        WERF_DIR: "ci"

  publish_werf_images:
    name: Publish images with werf by trdl group and channel
    needs: release
    runs-on: tfprod-werf
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build and publish werf images
      run: |
        docker login ghcr.io/werf/werf -u ${{ secrets.WERF_IN_IMAGE_REPO_LOGIN }} -p ${{ secrets.WERF_IN_IMAGE_REPO_PASSWORD }}
        . $(trdl use werf 1.2 stable)
        ./scripts/werf-in-image/build-and-publish.sh
