name: Website Deployment
on:
  repository_dispatch:
    types: [site-deploy]

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Deploy website to production
      run: |
        curl -X POST \
             -F "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
             -F "ref=main" \
             ${{ secrets.GITLAB_URL }}/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/trigger/pipeline
